import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TableOfContents from '../components/table-of-contents'

export default function Home({result}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Minimal Bible</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bible
        </h1>
        <TableOfContents/>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

